name = "microvision-modpack"
type = "service"
main = "index.js"

[[env.production.vars]]
ENV = "production"

[env.production]
routes = [
    { pattern = "microvision-modpack.bryan.ovh", zone_name = "bryan.ovh" }
]

[[r2_buckets]]
binding = "MICROVISION_MODPACK"
bucket_name = "microvision-modpack"
